name: Deploy on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22

          script: |
            
            cd /home/cb/projects/chetanbudathoki.com.np || exit 1
            
            git pull origin main || exit 1
            
            docker build -t chetanbudathoki .
            
            docker stop chetanbudathoki.com.np || true
            docker rm chetanbudathoki.com.np || true
            
            docker run -d --name chetanbudathoki.com.np -p 8002:80 chetanbudathoki
